name = "MPCCModels"
uuid = "cbaba3ef-cedb-4e5a-9903-71bbac24a74a"
version = "0.1.0"
authors = [
        "Anton E. Pozharskiy <anton@pozhar.ski>",
        "François Pacaud Pacaud <francoispacaud8@gmail.com>",
        "Armin Nurkanović <armin.nurkanovic@imtek.uni-freiburg.de>",
        ]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
LinearAlgebra = "1"
NLPModels = "0.21.12"
SparseArrays = "1"
Test = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[workspace]
projects = ["docs"]
